# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    http_cache: true
    cache:
        pools:
            portfolio.cache:
                adapter: cache.app
                tags: true
            cache.rate_limiter:
                adapter: cache.app
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
                
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        name: portfolio_session

    #esi: true
    #fragments: true

when@test:
    framework:
        http_cache: false
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
