docRoot                   $VH_ROOT/public

errorlog $VH_ROOT/../logs/error.log {
  useServer               0
  logLevel                ERROR
}

accesslog $VH_ROOT/../logs/access.log {
  useServer               0
}

index {
  useServer               0
  indexFiles              index.php
}

scripthandler {
  add lsapi:php php
}

extprocessor php {
  type                    lsapi
  address                 UDS://tmp/lshttpd/php.sock
  maxConns                10
  env                     PHP_LSAPI_CHILDREN=10
  initTimeout             60
  retryTimeout            0
  persistConn             1
  respBuffer              0
  autoStart               1
  path                    /usr/local/bin/lsphp
}

rewrite {
  enable                  1
  rules                   <<<END_RULES
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php [QSA,L]
  END_RULES
}