docRoot                   /var/www/api/public

rewrite  {
    enable                1
    autoLoadHtaccess      1
    rules                 <<<END_RULES
    rewriteCond %{REQUEST_FILENAME} !-f
    rewriteRule ^(.*)$ /index.php [QSA,L]
    END_RULES
}

context / {
    location              /var/www/api/public
    allowBrowse           0

    rewrite  {
        enable            1
    }

    phpIniOverride  {
        php_admin_value open_basedir /var/www/api
    }
}