parameters:

services:
    _defaults:
        autowire: true      
        autoconfigure: true 
        bind:
            $anonymousApiLimiter: '@limiter.anonymous_api'

    App\:
        resource: '../src/'

    App\OpenApi\PortfolioOpenApiDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments:
            $decorated: '@.inner'

    App\OpenApi\ImageUploadOpenApiDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments:
            $decorated: '@.inner'

    App\Service\ImageUploadService:
        arguments:
            $uploadDir: '%kernel.project_dir%/public/images'

    App\MessageHandler\SendContactEmailHandler:
        arguments:
            $emailTo: '%env(EMAIL_TO)%'

    Symfony\Contracts\Cache\TagAwareCacheInterface $portfolioCache:
        alias: portfolio.cache
