
parameters:

services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    App\:
        resource: '../src/'

    App\OpenApi\PortfolioOpenApiDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments:
            $decorated: '@.inner'

    App\OpenApi\ImageUploadOpenApiDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments:
            $decorated: '@.inner'

    App\Service\ImageUploadService:
        arguments:
            $uploadDir: '%kernel.project_dir%/public/images'
